<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class SitePostsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('site_posts')->insert(array (
  0 => 
  array (
    'id' => 1,
    'created_at' => '2024-08-01 10:34:42',
    'updated_at' => '2024-08-01 10:34:42',
    'enable' => NULL,
    'code' => NULL,
    'slug' => NULL,
    'name' => NULL,
    'email' => NULL,
    'password' => NULL,
    'categories' => NULL,
    'keyword' => NULL,
    'tags' => NULL,
    'title' => 'ㅇㄻㄴㄻㄴㅇㄹ',
    'content' => 'ㄻㄴㅇㄹㄴㅁㅇㄻㄴㅇ',
    'image' => NULL,
    'click' => 1,
    'like' => 0,
    'rank' => 0,
  ),
  1 => 
  array (
    'id' => 2,
    'created_at' => '2024-08-01 10:39:44',
    'updated_at' => '2024-08-01 10:39:44',
    'enable' => NULL,
    'code' => NULL,
    'slug' => NULL,
    'name' => NULL,
    'email' => NULL,
    'password' => NULL,
    'categories' => NULL,
    'keyword' => NULL,
    'tags' => NULL,
    'title' => 'ㄻㅇㄴㄻㄴㅇㄹ',
    'content' => 'ㅇㄻㄴㅇㄻㄴㅇㄹ',
    'image' => NULL,
    'click' => 1,
    'like' => 0,
    'rank' => 0,
  ),
  2 => 
  array (
    'id' => 3,
    'created_at' => '2024-08-01 10:39:52',
    'updated_at' => '2024-08-01 10:39:52',
    'enable' => NULL,
    'code' => NULL,
    'slug' => NULL,
    'name' => NULL,
    'email' => NULL,
    'password' => NULL,
    'categories' => NULL,
    'keyword' => NULL,
    'tags' => NULL,
    'title' => '1111',
    'content' => '11111',
    'image' => NULL,
    'click' => 0,
    'like' => 0,
    'rank' => 0,
  ),
  3 => 
  array (
    'id' => 4,
    'created_at' => '2024-08-01 10:40:02',
    'updated_at' => '2024-08-01 10:40:02',
    'enable' => NULL,
    'code' => NULL,
    'slug' => NULL,
    'name' => NULL,
    'email' => NULL,
    'password' => NULL,
    'categories' => NULL,
    'keyword' => NULL,
    'tags' => NULL,
    'title' => '2222',
    'content' => '22222',
    'image' => NULL,
    'click' => 0,
    'like' => 0,
    'rank' => 0,
  ),
  4 => 
  array (
    'id' => 5,
    'created_at' => '2024-08-02 05:33:14',
    'updated_at' => '2024-08-02 05:33:14',
    'enable' => NULL,
    'code' => NULL,
    'slug' => NULL,
    'name' => NULL,
    'email' => NULL,
    'password' => NULL,
    'categories' => NULL,
    'keyword' => NULL,
    'tags' => NULL,
    'title' => 'ㄱㅈㅂㄷㄱㅈㄷㅂㄱ',
    'content' => 'ㄷㄱㅈㅂㄷㄱㅈㄷㅂㄱㅂㅈㄷㄱㅂㅈㄷㄱ',
    'image' => NULL,
    'click' => 0,
    'like' => 0,
    'rank' => 0,
  ),
  5 => 
  array (
    'id' => 9,
    'created_at' => '2024-08-02 06:03:16',
    'updated_at' => '2024-08-02 06:03:16',
    'enable' => NULL,
    'code' => NULL,
    'slug' => NULL,
    'name' => NULL,
    'email' => NULL,
    'password' => NULL,
    'categories' => NULL,
    'keyword' => NULL,
    'tags' => NULL,
    'title' => 'ㅀㄴㅇㅀㄴㅇㄹㅀㄴㅇㅀㄴ',
    'content' => 'ㄴㅇㅀㄴㅇㅀㄹㅇㅎㄴㅇㅀ',
    'image' => NULL,
    'click' => 0,
    'like' => 0,
    'rank' => 0,
  ),
  6 => 
  array (
    'id' => 11,
    'created_at' => '2024-08-02 06:48:18',
    'updated_at' => '2024-08-02 06:48:18',
    'enable' => NULL,
    'code' => NULL,
    'slug' => NULL,
    'name' => NULL,
    'email' => NULL,
    'password' => NULL,
    'categories' => NULL,
    'keyword' => NULL,
    'tags' => NULL,
    'title' => 'gsdfgsdf',
    'content' => 'fdsgsdfg',
    'image' => 'upload/Xus5sATMdtV9koYtKisuLR2hEe0zuQrepANHMs9d.jpg',
    'click' => 0,
    'like' => 0,
    'rank' => 0,
  ),
  7 => 
  array (
    'id' => 12,
    'created_at' => '2024-08-02 06:55:41',
    'updated_at' => '2024-08-02 06:55:41',
    'enable' => NULL,
    'code' => NULL,
    'slug' => NULL,
    'name' => NULL,
    'email' => NULL,
    'password' => NULL,
    'categories' => NULL,
    'keyword' => NULL,
    'tags' => NULL,
    'title' => 'gfdgdfsg',
    'content' => 'fgsdfgsdg',
    'image' => 'upload/posts/h4FXxyhbzAzeYKxo3SXZAQzpKStOsico2ZkWnYHJ.jpg',
    'click' => 0,
    'like' => 0,
    'rank' => 0,
  ),
  8 => 
  array (
    'id' => 15,
    'created_at' => '2024-08-02 07:42:09',
    'updated_at' => '2024-08-02 07:42:09',
    'enable' => NULL,
    'code' => NULL,
    'slug' => NULL,
    'name' => NULL,
    'email' => NULL,
    'password' => NULL,
    'categories' => NULL,
    'keyword' => NULL,
    'tags' => NULL,
    'title' => 'ㅎㄹㅇㄶㄴㅇㄹ',
    'content' => 'ㅎㄴㅇㅀㄴㅇㅀ',
    'image' => 'images/Nm2C7PjRKjUsu7rVJmpw43V5SY851hpGQOx28cJ1.jpg',
    'click' => 1,
    'like' => 0,
    'rank' => 0,
  ),
  9 => 
  array (
    'id' => 18,
    'created_at' => '2024-08-02 07:58:43',
    'updated_at' => '2024-08-02 07:58:43',
    'enable' => NULL,
    'code' => NULL,
    'slug' => NULL,
    'name' => NULL,
    'email' => NULL,
    'password' => NULL,
    'categories' => NULL,
    'keyword' => NULL,
    'tags' => NULL,
    'title' => 'dfasf',
    'content' => 'dsafasdfa',
    'image' => 'images/yy1JkmgiOdhHC9kMswSmFcOMr5UOgVMi2SrrmnIh.jpg',
    'click' => 1,
    'like' => 0,
    'rank' => 0,
  ),
  10 => 
  array (
    'id' => 19,
    'created_at' => '2024-08-02 07:59:22',
    'updated_at' => '2024-08-02 07:59:22',
    'enable' => NULL,
    'code' => NULL,
    'slug' => NULL,
    'name' => NULL,
    'email' => NULL,
    'password' => NULL,
    'categories' => NULL,
    'keyword' => NULL,
    'tags' => NULL,
    'title' => 'adsfasdf',
    'content' => 'dfasdfas',
    'image' => 'images/Jsdk1qcuoeHJQYrig8yjUtnM9Ax1fYtKA4pWMMzF.jpg',
    'click' => 0,
    'like' => 0,
    'rank' => 0,
  ),
  11 => 
  array (
    'id' => 20,
    'created_at' => '2024-08-02 08:00:40',
    'updated_at' => '2024-08-02 08:00:40',
    'enable' => NULL,
    'code' => NULL,
    'slug' => NULL,
    'name' => NULL,
    'email' => NULL,
    'password' => NULL,
    'categories' => NULL,
    'keyword' => NULL,
    'tags' => NULL,
    'title' => 'dsfdsa',
    'content' => 'dfasdfasd',
    'image' => NULL,
    'click' => 0,
    'like' => 0,
    'rank' => 0,
  ),
  12 => 
  array (
    'id' => 21,
    'created_at' => '2024-08-02 08:01:49',
    'updated_at' => '2024-08-02 08:01:49',
    'enable' => NULL,
    'code' => NULL,
    'slug' => NULL,
    'name' => NULL,
    'email' => NULL,
    'password' => NULL,
    'categories' => NULL,
    'keyword' => NULL,
    'tags' => NULL,
    'title' => 'rtwewert',
    'content' => 'twertwert',
    'image' => 'images/QOhhDaDmU2aNr7zToBKQSnHM1uipcJqcit5IGMEe.jpg',
    'click' => 0,
    'like' => 0,
    'rank' => 0,
  ),
  13 => 
  array (
    'id' => 22,
    'created_at' => '2024-08-02 08:03:04',
    'updated_at' => '2024-08-02 08:03:04',
    'enable' => NULL,
    'code' => NULL,
    'slug' => NULL,
    'name' => NULL,
    'email' => NULL,
    'password' => NULL,
    'categories' => NULL,
    'keyword' => NULL,
    'tags' => NULL,
    'title' => 'dgasads',
    'content' => 'fgsdfg',
    'image' => 'posts/a2OYfuVom7lNsWU60vgTJJN53DkPjUbAbdPdgsEG.jpg',
    'click' => 0,
    'like' => 0,
    'rank' => 0,
  ),
  14 => 
  array (
    'id' => 23,
    'created_at' => '2024-08-02 08:04:09',
    'updated_at' => '2024-08-02 08:04:09',
    'enable' => NULL,
    'code' => NULL,
    'slug' => NULL,
    'name' => NULL,
    'email' => NULL,
    'password' => NULL,
    'categories' => NULL,
    'keyword' => NULL,
    'tags' => NULL,
    'title' => 'gdsgagd',
    'content' => 'dgasdgas',
    'image' => 'upload/posts/a89uj18IeXeXQqMgtBXIHv4tzuW1t2V0Csa6eoLk.jpg',
    'click' => 0,
    'like' => 0,
    'rank' => 0,
  ),
  15 => 
  array (
    'id' => 24,
    'created_at' => '2024-08-02 08:07:52',
    'updated_at' => '2024-11-11 10:35:31',
    'enable' => NULL,
    'code' => NULL,
    'slug' => NULL,
    'name' => NULL,
    'email' => NULL,
    'password' => NULL,
    'categories' => NULL,
    'keyword' => NULL,
    'tags' => NULL,
    'title' => 'fgsdfgsdf1234',
    'content' => 'fgsdfgsdf1111',
    'image' => '/images/upload/posts/GdJUDz9KrPCxtDDkPcZlb9gipA5nnwq6OuAhaQiW.jpg',
    'click' => 2,
    'like' => 0,
    'rank' => 0,
  ),
  16 => 
  array (
    'id' => 25,
    'created_at' => '2024-08-02 08:10:58',
    'updated_at' => '2024-10-31 06:41:24',
    'enable' => '1',
    'code' => '111',
    'slug' => 'aaa',
    'name' => NULL,
    'email' => NULL,
    'password' => NULL,
    'categories' => NULL,
    'keyword' => NULL,
    'tags' => NULL,
    'title' => 'gfsgd111222',
    'content' => 'gfsdfgsdfg
dfajsdflkjasdf
lkjdsalkfjklasd
lkfjalskdf',
    'image' => '/images/upload/posts/1IP7OS4NFIXo1pZJZL1X1nghyn9wpePMwIkfktl5.jpg',
    'click' => 37,
    'like' => 0,
    'rank' => 0,
  ),
));
    }
}
