<?php
return [
	'updated_at'=>"2025-01-07 10:20:44",
	'description'=>"\\u3147\\u313b\\u3134\\u3147\\u313b\\u3134\\u3139",
	'auth'=>[
		'enable'=>"",
		'auto'=>"1"
	],
	'register'=>"1",
	'agreement'=>"1",
	'view'=>[
		'agreement'=>"jiny-auth::agreement"
	],
	'login'=>[
		'view'=>"",
		'enable'=>"1",
		'log'=>"1",
		'remember'=>"1"
	],
	'view_login'=>"",
	'view_regist'=>"",
	'logout'=>"/",
	'dashboard'=>"/",
	'remember'=>"1",
	'password_period'=>"3",
	'home'=>"/",
	'agree'=>[
		'enable'=>""
	],
	'success'=>[
		'enable'=>"1"
	],
	'regist'=>[
		'enable'=>"1",
		'mail'=>"1",
		'verified'=>"1",
		'success'=>"1"
	],
	'verified'=>[

	],
	'sleeper'=>[
		'enable'=>"1",
		'auto'=>""
	],
	'password'=>[
		'min'=>"8",
		'special'=>"",
		'number'=>"",
		'period'=>"2"
	]
];